config/routes.rb
Rails.application.routes.draw do
  #get 'sessions/new'

  get 'authors/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to: 'home#index'
  resources :customers
  resources :books
  resources :publishers
  resources :authors
  resources :categories
  resources :categorizations
  resources :home

  get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "customers#new", :as => "sign_up"
#root :to => "customers#new"
resources :sessions

#root to: 'customers#new'
  #root to: 'home#index'
  root to: 'home#index'

end

app/models/author.rb
class Author < ApplicationRecord
has_many :books

def self.search(search)
  if search
   # find( "author_name LIKE ? ", "%#{search}%")
   where( "author_name LIKE ? ", "%#{search}%")

  
  else
    all
  end
end

end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  def index
@authors = Author.all
#@message = "Hello"
  end
  
  def new
    @author = Author.new
  end
  
  def edit
  end
  
  def create
    @author = Author.new(author_params)
    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @author = Author.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:author).permit(:title, :body)
    end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
  # @publisher = Publisher.find(1)
#  @books = @publisher.books.all
    
@authors = Author.all

#@message = "Hello"
  end
  
  def show
  end
  
  def new
    @author = Author.new
  end
  
  def edit
  end
  
  def create
    @author = Author.new(author_params)
    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
       @author = Author.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:author_name, :biography, :photo)
    end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for(author) do |f| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <form class="form-horizontal">
  <div class="form-group">
    <%= f.label :author_name %>
    <%= f.text_field :author_name %>
  </div>
  
  <div class="form-group">
    <%= f.label :biography%>
    <%= f.text_area :biography%>
  </div>
 <div class="form-group">
    <%= f.label :photo%>
    <%= f.text_area :photo%>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>div>

app/views/authors/edit.html.erb
<h1>Editing </h1>
<%= render 'form', author: @author %>
<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <tr>
    <th>Name</th>
   
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.author_name %></td>
    <td><%= link_to 'Show', author %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    
  </tr>
<% end %>
</table>
  
<br />

  <%= link_to 'New author', new_author_path %>   
  
  <br />

  <br />

  

app/views/authors/new.html.erb
<h1>New </h1>
<%= render 'form', author: @author %>
<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @author.author_name %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>