config/routes.rb
Rails.application.routes.draw do
  #get 'sessions/new'

  get 'authors/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to: 'home#index'
  resources :customers
  resources :books
  resources :publishers
  resources :authors
  resources :categories
  resources :categorizations
  resources :home

  get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "customers#new", :as => "sign_up"
#root :to => "customers#new"
resources :sessions

#root to: 'customers#new'
  #root to: 'home#index'
  root to: 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
@customers = Customer.all
#@message = "Hello"
  end
  
  def show
  end
  
  def new
    @customer = Customer.new
  end
  
  def edit
  end
  
  def create
    @customer = Customer.new(customer_params)
    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:customer_name, :email)
    end

end

#  def index
 # end
#end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!--banner-->
<script src="js/responsiveslides.min.js"></script>
<script>  
    $(function () {
      $("#slider").responsiveSlides({
      	auto: true,
      	nav: true,
      	speed: 500,
        namespace: "callbacks",
        pager: true,
      });
    });
</script>

<div class="banner-bg banner-bg1">	
	  <div class="container">
			 <div class="header">					 
				  <div class="top-nav">										 
						<label class="mobile_menu" for="mobile_menu">
						<span>Menu</span>
						</label>
						<input id="mobile_menu" type="checkbox">
					   <ul class="nav">
					   	<li class="dropdown1"><a href="index.html">HOME</a>
						  </li>
						  <li class="dropdown1"><%= link_to "BOOKSTORE", books_path%></a>
						  </li>
						  <li class="dropdown1"><a class="shop scroll" href="#cate">CATEGORIES</a>
							 <ul class="dropdown2">
							 		<li><a href=#>CLASSIC</a></li>
									<li><a href=#>DETECTIVE NOVEL</a></li>
									<li><a href=#>DRAMA AND ROMANCE</a></li>
									<li><a href=#>ACTION AND ADVERTURE</a></li>
									<li><a href="#">SCIENCE FICTION & FANTASY</a></li>
									<li><a href=#>HORROR</a></li>
							  </ul>
						 </li>               
						 <li class="dropdown1"> <%= link_to "LOG IN", log_in_path %></a>
							 <ul class="dropdown2">
									<li> <td><%= link_to 'SIGN UP', new_customer_path %></td></li>
									<li><a href="#">CONTACT WITH US</a></li>
									<li><%= link_to "log in", log_in_path %></a></li>
							  </ul>
						 </li>
						  <a class="shop" href="#"><img src="images/cart.png" alt=""/></a>
					  </ul>
				 </div>
				 <div class="clearfix"></div>
			 </div>
	  </div>	 
	 <div class="caption">
		 <div class="slider">
					   <div class="callbacks_container">
						   <ul class="rslides" id="slider">
							    <li><h1>ANOTHER WORLD</h1></li>
								<li><h1>ANOTHER PEOPLE</h1></li>	
								<li><h1>ANOTHER STORY</h1></li>	
						  </ul>
						  <p>A <span>book</span> is <span>a dream,</span> that you hold in <span>your hand</span></p>
						  <a class="morebtn"> <%= link_to "SHOP BOOKS", books_path%></a>
					  </div>
				  </div>
	 </div>
	 <div class="dwn">
		<a class="scroll" href="#cate"><img src="images/scroll.png" alt=""/></a>
	 </div>				 
</div>
<!--/banner-->
<div id="cate" class="categories">
	 <div class="container">
		 <h3>CATEGORIES</h3>
		 <div class="categorie-grids">
			 <a href="bicycles.html"><div class="col-md-4 cate-grid grid1">
				 <h4>CLASSIC</h4>
				 <p></p>
				 <a class="store" href="bicycles.html">GO TO STORE</a>
			 </div></a>
			 <a href="bicycles.html"><div class="col-md-4 cate-grid grid2">
				 <h4>DETECTIVE NOVEL</h4>
				 <p></p>
				 <a class="store" href="bicycles.html">GO TO STORE</a>
			 </div></a>
			 <a href="bicycles.html"><div class="col-md-4 cate-grid grid1">
				 <h4>DRAMA AND ROMANCE</h4>
				 <p></p>
				 <a class="store" href="bicycles.html">GO TO STORE</a>
			 </div></a>
			 <a href="bicycles.html"><div class="col-md-4 cate-grid grid2">
				 <h4>ACTION AND ADVERTURE</h4>
				 <p></p>
				 <a class="store" href="bicycles.html">GO TO STORE</a>
			 </div></a>
			 <a href="bicycles.html"><div class="col-md-4 cate-grid grid1">
				 <h4>SCIENCE FICTION & FANTASY</h4>
				 <p></p> 
				 <a class="store" href="bicycles.html">GO TO STORE</a>
			 </div></a>
			 <a href="bicycles.html"><div class="col-md-4 cate-grid grid2">
				 <h4>HORROR</h4>
				 <p></p>
				 <a class="store" href="bicycles.html">GO TO STORE</a>
			 </div></a>
			 <div class="clearfix"></div>
		 </div>
	 </div>
</div>
<!--bikes-->
<div class="bikes">	
		 <h3>POPULAR BOOKS</h3>
		 <div class="bikes-grids">			 
			 <ul id="flexiselDemo1">
				 <li>
					 <img src="/images/book1.jpg" width="250" alt=""/>
					 <div class="bike-info">
							 <h4>FIXED GEAR FIXED GEAR<span>$249.00</span></h4>				
						 <div class="clearfix"></div>
					 </div>
					 <div class="viw">
						<a href="bicycles.html">Quick View</a>
					 </div>
				 </li>
				 <li>
				 <img src="/images/book2.jpg" width="250" alt=""/>
				 <div class="bike-info">
							 <h4>BIG BOY ULTRA<span>$249.00</span></h4>							 	
						 <div class="clearfix"></div>
					 </div>
					 <div class="viw">
						<a href="bicycles.html">Quick View</a>
					 </div>
				 </li>
				 <li>
					<img src="/images/book3.jpg" width="250" alt=""/>
					 <div class="bike-info">
							 <h4>ROCK HOVER ROCK HOVER<span>$300.00</span></h4>					
						 <div class="clearfix"></div>
					 </div>
					 <div class="viw">
						<a href="bicycles.html">Quick View</a>
					 </div>
				 </li>
				 <li>
				     <img src="/images/book4.jpg" width="250" alt=""/>
					 <div class="bike-info">
							 <h4>SANSACHG<span>$249.00</span></h4>
						 <div class="clearfix"></div>
					 </div>
					 <div class="viw">
						<a href="bicycles.html">Quick View</a>
					 </div>
				 </li>
				 <li>
					 <img src="/images/book5.jpg" width="250" alt=""/>
					 <div class="bike-info">
							 <h4>JETT MAC<span>$340.00</span></h4>
						 <div class="clearfix"></div>
					 </div>
					 <div class="viw">
						<a href="bicycles.html">Quick View</a>
					 </div>
				 </li>
				 <li>
				      <img src="/images/book6.jpg" alt=""/>
					  <div class="bike-info">
							 <h4>SANSACHG<span>$249.00</span></h4>
						 <div class="clearfix"></div>
					 </div>
					 <div class="viw">
						<a href="bicycles.html">Quick View</a>
					 </div>
				 </li>
		    </ul>
			<script type="text/javascript">
			 $(window).load(function() {			
			  $("#flexiselDemo1").flexisel({
				visibleItems: 5,
				animationSpeed: 1000,
				autoPlay: true,
				autoPlaySpeed: 3000,    		
				pauseOnHover:true,
				enableResponsiveBreakpoints: true,
				responsiveBreakpoints: { 
					portrait: { 
						changePoint:480,
						visibleItems: 1
					}, 
					landscape: { 
						changePoint:640,
						visibleItems: 2
					},
					tablet: { 
						changePoint:768,
						visibleItems: 3
					}
				}
			});
			});
			</script>
			<script type="text/javascript" src="js/jquery.flexisel.js"></script>			 
	</div>
</div>
<!---->
<div class="contact">
	<div class="container">
		<h3>CONTACT US</h3>
		<p>Please contact us for all inquiries and purchase options.</p>
		<form>
			 <input type="text" placeholder="NAME" required="">
			 <input type="text" placeholder="SURNAME" required="">			 
			 <input class="user" type="text" placeholder="USER@DOMAIN.COM" required=""><br>
			 <textarea placeholder="MESSAGE"></textarea>
			 <input type="submit" value="SEND">
		</form>
	</div>
</div>
<!---->
<div class="footer">
	 <div class="container wrap">
		<div class="ftr-menu">
			 <ul>
			 	 <li><a href="index.html">HOME</a></li>
				 <li><a href="books#index">BOOKSTORE</a></li>
				 <li><a href="#">CATEGORIES</a></li>
				 <li><%= link_to "LOG IN", log_in_path %></a></li>
			 </ul>
		</div>
		<div class="clearfix"></div>
	 </div>
</div>
<!---->

app/views/home/registration.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Book Shop a Ecommerce Category Flat Bootstarp Responsive Website Template| Home </title>
<meta charset="utf-8">
<link href="css/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- jQuery (Bootstrap's JavaScript plugins) -->
<script src="js/jquery.min.js"></script>
<!-- Custom Theme files -->
<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Book-shop Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--webfont-->
<link href='http://fonts.googleapis.com/css?family=Roboto:500,900,100,300,700,400' rel='stylesheet' type='text/css'>
<!--webfont-->
<!-- dropdown -->
<script src="js/jquery.easydropdown.js"></script>
<link href="css/nav.css" rel="stylesheet" type="text/css" media="all"/>
<script src="js/scripts.js" type="text/javascript"></script>

<!--js-->
<!---- start-smoth-scrolling---->
		<script type="text/javascript" src="js/move-top.js"></script>
		<script type="text/javascript" src="js/easing.js"></script>
		<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){		
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},900);
				});
			});
		</script>
<!---- start-smoth-scrolling---->
		<script type="text/javascript">
			jQuery(document).ready(function() {

				$(':text:first').focus();
				
				$('#confirm_password').change(function() {
			      var pass1 = $("#password").val();
			      var pass2 = $("#confirm_password").val();
				  
			      if (pass1 != pass2) {
					$("#confirm_password").css('border', 'red 3px solid');
			      }
			      if (pass1 == pass2) {
					$("#confirm_password").css('border', 'green 3px solid');
			      }
				});
			});
		</script>

</head>
<body>
<!--banner-->
<script src="js/responsiveslides.min.js"></script>
<script>  
    $(function () {
      $("#slider").responsiveSlides({
      	auto: true,
      	nav: true,
      	speed: 500,
        namespace: "callbacks",
        pager: true,
      });
    });
 </script>
<div class="banner-bg banner-bg1">	
	  <div class="container">
			 <div class="header">						 
				  <div class="top-nav">										 
						<label class="mobile_menu" for="mobile_menu">
						<span>Menu</span>
						</label>
						<input id="mobile_menu" type="checkbox">
					   <ul class="nav">
					   	<li class="dropdown1"><a href="index.html">HOME</a>
						  </li>
						  <li class="dropdown1"><a href=#>BOOKSTORE</a>
						  </li>
						  <li class="dropdown1"><a href="index.html">CATEGORIES</a>
							 <ul class="dropdown2">
							 		<li><a href=#>CLASSIC</a></li>
									<li><a href=#>DETECTIVE NOVEL</a></li>
									<li><a href=#>DRAMA AND ROMANCE</a></li>
									<li><a href=#>ACTION AND ADVERTURE</a></li>
									<li><a href="#">SCIENCE FICTION & FANTASY</a></li>
									<li><a href=#>HORROR</a></li>
							  </ul>
						 </li>               
						 <li class="dropdown1"><a href="#">LOG IN</a>
							 <ul class="dropdown2">
									<li><a href="registration.html">SING UP</a></li>
									<li><a href="#">CONTACT WITH US</a></li>
							  </ul>
						 </li>
						  <a class="shop" href="#"><img src="#{assets_path('cart.png')}" alt=""/></a>
					  </ul>
				 </div>
				 <div class="clearfix"></div>
			 </div>
	  </div>	 
	 <div class="registration">

			<form action="">
			<fieldset class="data">
				 <p><label for="user">FIRST NAME</label>
				 <input name="user" class="field name" type="text" required pattern="^[A-Za-zА-Яа-яЁё]+$": :customer_name>
				 <span></span>
				 <br>
				 <label for="surname">SECOND NAME</label>
				 <input name="surname" class="field surname" type="text" required pattern="^[A-Za-zА-Яа-яЁё]+$">
				 <span></span>
				 <br>
				 <label for="phonenumber">PHONE NUMBER</label>
				 <input name="phonenumber" class="field city" type="text" required pattern="+[0-9]{12}"+$">
				 <span></span></p>
				 <label for="city">ADDRESS</label>
				 <input name="city" class="field city" type="text" required pattern="^[A-Za-zА-Яа-я0-9Ёё\s.,]+$">
				 <span></span></p>
				 <p><label for="email">EMAIL</label>
				 <input name="email" class="field email" required type="email">
				 <span></span>
				 <br>
				 <label for="pass">PASSWORD</label>
				 <input name="pass" id="password" class="field password1" type="password" id="password">
				 <br>
				 <label for="pass-repeat">REPEAT</label>
				 <input name="pass-repeat" id="confirm_password" class="field password2" type="password" required></p>
			</fieldset>
			<div class="check"><button id="submit"></button>
			</form>

	 </div>
</div>

<!---->
<!---->
</body>
</html>