config/routes.rb
Rails.application.routes.draw do
  #get 'sessions/new'

  get 'authors/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to: 'home#index'
  resources :customers
  resources :books
  resources :publishers
  resources :authors
  resources :categories
  resources :categorizations
  resources :home

  get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "customers#new", :as => "sign_up"
#root :to => "customers#new"
resources :sessions

#root to: 'customers#new'
  #root to: 'home#index'
  root to: 'home#index'

end

app/models/customer.rb
class Customer < ApplicationRecord
has_many :authorization_orders

#attr_accessible :email, :password, :password_confirmation

  
  attr_accessor :password
  attr_reader :password_hash
  #before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of	 :email
  
  def self.authenticate(email, password)
    customer = find_by_email(email)
    if customer #&& customer.password_hash == BCrypt::Engine.hash_secret(password, customer.password_salt)
      customer
    else
      nil
    end
  end
  

end

#end
#class Customer < ActiveRecord::Base
#validates :name, presence: true
#end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
@customers = Customer.all
#@message = "Hello"
  end
  
  def show
  end
  
  def new
    @customer = Customer.new
  end
  
  def edit
  end
  
  def create
    @customer = Customer.new(customer_params)
    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
        #redirect_to root_url, :notice => "Signed up!"
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:customer_name, :email, :password,:phone_number, :adress)
    end

end

app/views/customers/_form.html.erb
<% customer = Customer.new %>
<%= bootstrap_form_for(customer) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>
      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>  /
  <% end %>
  <!--
  <form class="form-horizontal" 
    <div class = "form-group">
    <div class="col-xs-10">
        <%= f.text_field :customer_name,  class: 'form-control' %>
    </div>
    </div>
    <div class="form-group">
        <div class="col-xs-10">
        <%= f.text_field :phone_number, class: 'form-control'  %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-xs-10">
      <%= f.text_field :adress, class: 'form-control'  %>
      </div>
    </div>
    <div class="form-group">
        <div class="col-xs-10">
        <%= f.email_field :email, class: 'form-control'  %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-10">
        <%= f.password_field :password, class: 'form-control'  %>
        </div>
    </div>

    </form>
    -->

  <form class="form-horizontal">
  <div class="form-group">
    <label class="col-sm-2 control-label">Customer name</label>
    <div class="col-sm-10">
      <%= f.text_field :customer_name, hide_label: true %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Telephone</label>
    <div class="col-sm-10">
      <%= f.text_field :phone_number, hide_label: true, class: 'form-control'  %>
    </div>
  </div>
   <div class="form-group">
    <label class="col-sm-2 control-label">Adress</label>
    <div class="col-sm-10">
      <%= f.text_field :adress, hide_label: true, class: 'form-control'  %>
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmaild3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
      <%= f.email_field :email, hide_label: true, class: 'form-control'  %>
    </div>
  </div>
   <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
      <%= f.password_field :password, hide_label: true, class: 'form-control'  %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Submit", class: "btn btn-outlined btn-primary" %>
    </div>
  </div>
  </form>

<% end %>

app/views/customers/edit.html.erb
<h1>Editing Post</h1>
<%= render 'form', customer: @customer %>
<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%= customer.customer_name %></td>
    <td><%= customer.email %></td>
   <td><%= link_to 'Show', customer %></td>
    <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
    <td><%= link_to 'Destroy',customer, method: :delete,
                                     data: { confirm: 'Are you sure?' } %></td>  
  </tr>
<% end %>
</table>
  
<br />

  <%= link_to 'New customer', new_customer_path %>   

app/views/customers/new.html.erb
<div class="banner-bg banner-bg1">  
    <div class="container">
       <div class="header">            
          <div class="top-nav">                    
            <label class="mobile_menu" for="mobile_menu">
            <span>Menu</span>
            </label>
            <input id="mobile_menu" type="checkbox">
             <ul class="nav">
              <li class="dropdown1"><a href="index.html">HOME</a>
              </li>
              <li class="dropdown1"><a href="bookstore.html">BOOKSTORE</a>
              </li>
              <li class="dropdown1"><a href="categories.html">CATEGORIES</a>
               <ul class="dropdown2">
                  <li><a href=#>CLASSIC</a></li>
                  <li><a href=#>DETECTIVE NOVEL</a></li>
                  <li><a href=#>DRAMA AND ROMANCE</a></li>
                  <li><a href=#>ACTION AND ADVERTURE</a></li>
                  <li><a href="#">SCIENCE FICTION & FANTASY</a></li>
                  <li><a href=#>HORROR</a></li>
                </ul>
             </li>               
             <li class="dropdown1"><a href="#">LOG IN</a>
               <ul class="dropdown2">
                  <li><a href="registration.html">SING UP</a></li>
                  <li><a href="#">CONTACT WITH US</a></li>
                </ul>
             </li>
              <a class="shop" href="#"><img src="images/cart.png" alt=""/></a>
            </ul>
         </div>
         <div class="clearfix"></div>
       </div>
    </div>   




      <div class "regwindow">
        <%= render 'form', customer: @customer %>
      </div>



</div>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @customer.customer_name %>
</p>
<p>
  <strong>Body:</strong>
  <%= @customer.email %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>