config/routes.rb
Rails.application.routes.draw do
  #get 'sessions/new'

  get 'authors/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to: 'home#index'
  resources :customers
  resources :books
  resources :publishers
  resources :authors
  resources :categories
  resources :categorizations
  resources :home

  get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "customers#new", :as => "sign_up"
#root :to => "customers#new"
resources :sessions

#root to: 'customers#new'
  #root to: 'home#index'
  root to: 'home#index'

end

app/models/book.rb
class Book < ApplicationRecord
belongs_to :author
has_many :categorizations
  has_many :categories, through: :categorizations 
belongs_to :publisher
has_many :order_items

def self.search(search)
  if search
    where( "book_name LIKE ? ", "%#{search}%")
  else
    all
  end
end

def self.a_search(a_id)
  if a_id
  	where( author_id: "%#{a_id}%")
    
  else
    all
  end
end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
  # @publisher = Publisher.find(1)
#  @books = @publisher.books.all


   @authors=Author.all
   @books=[]
@authors=@authors.search(params[:a_search])
@authors.each do |author|
@books+= author.books.search(params[:search])
end



#@author=@authors.first

#@books = Book.all
#@books = @author.books
#@books = @books.all
#@books = @books.search(params[:search])
#@author=Author.search(params[:a_search])
#:a_id = "%#{@author.id}%"
#@books = @author.books.all
#@books = @books.a_search(5)
#@books = Book.all.where()
#@category=Category.find(params[:cat])
#@books = Book.includes(:categories).where(categories: { id: 5 })
#@category=Category.find(2) if params[:classic]
#@books = @books.category_search(params[:classic])#,params[:detective],params[:drama],params[:action],params[:science],params[:horror])
#@books = @books.search1(params[:search1])
#@message = "Hello"
  end
  
  def show
  end
  
  def new
    @book = Book.new
  end
  
  def edit
  end
  
  def create
    @book = Book.new(book_params)
  

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
       # category = Category.find(params[:category_id])
       # book.categories << category
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
        category = Category.find(params[:category_id])
        book.categories << category
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:book_name, :rating, :publisher_id,:publishing_year, :description, :photo, :price, :quantity, :quantity, :author_id, :size, :category_id)
    end

end

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<form class="form-horizontal">
  <div class="form-group">
    <%= f.label :book_name %>
    <%= f.text_field :book_name %>
  </div>
<div class="form-group">
    <%= f.label :rating%>
    <%= f.text_area :rating%>
    <div class="form-group">
    <%= f.label :author_id%>
    <%= f.text_area :author_id%>
  </div>
  </div>
  <div class="form-group">
    <%= f.label :publisher_id %>
    <%= f.text_area :publisher_id %>
  </div>
  <div class="form-group">
    <%= f.label :publishing_year%>
    <%= f.text_area :publishing_year%>
  </div>
 <div class="form-group">
    <%= f.label :description%>
    <%= f.text_area :description%>
  </div>
 <div class="form-group">
    <%= f.label :photo%>
    <%= f.text_area :photo%>
  </div>
 <div class="form-group">
    <%= f.label :price%>
    <%= f.text_area :price%>
  </div>
<div class="form-group">
    <%= f.label :quantity%>
    <%= f.text_area :quantity%>
  </div>
 
 <div class="form-group">
    <%= f.label :size%>
    <%= f.text_area :size%>
     </div>
    
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>
<%= render 'form', book: @book %>
<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Publisher</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.book_name %></td>
    <td><%= book.author.author_name  %></td>
   <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    
  </tr>
<% end %>
</table>
  
<br />

  <%= link_to 'New book', new_book_path %>   
  
  <br />

  <br />


  <%= form_tag books_path, :method => 'get' do %>
  <%= label_tag(:search, "Search for:") %>
     <%= text_field_tag  :search, params[:search]   %>
     

  <%= label_tag(:a_search, "Search for author:") %>
     <%= text_field_tag  :a_search, params[:a_search]   %>

     <%= radio_button_tag(:search1, "1") %>
<%= label_tag(1, "1") %>
<%= radio_button_tag(:search1, "2") %>
<%= label_tag(2, "2") %>
  <%= submit_tag "Search", :name => nil %>
  <% end %>
  <%#= link_to "Cat", categorizations_path%>
  

app/views/books/new.html.erb
<h1>New Book</h1>
<%= render 'form', book: @book %>
<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<script src="js/jquery.min.js"></script>
<!-- Custom Theme files -->
<link href="css/form.css" rel="stylesheet" type="text/css" media="all" />
<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Bike-shop Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--webfont-->
<link href='http://fonts.googleapis.com/css?family=Roboto:500,900,100,300,700,400' rel='stylesheet' type='text/css'>
<!--webfont-->
<!-- dropdown -->
<script src="js/jquery.easydropdown.js"></script>
<link href="css/nav.css" rel="stylesheet" type="text/css" media="all"/>
<script src="js/scripts.js" type="text/javascript"></script>
<!--js-->

</head>
<body>
<!--banner-->
<script src="js/responsiveslides.min.js"></script>

<div class="banner-bg banner-sec">	
	  <div class="container">
			 <div class="header">
						 
				  <div class="top-nav">										 
						<label class="mobile_menu" for="mobile_menu">
						<span>Menu</span>
						</label>
						<input id="mobile_menu" type="checkbox">
					   <ul class="nav">
						  <li class="dropdown1"><a href="index.html">HOME</a>
						  </li>
						  <li class="dropdown1"><a href="bookstore.html">BOOKSTORE</a>
						  </li>
						  <li class="dropdown1"><a href="categories.html">CATEGORIES</a>
							 <ul class="dropdown2">
							 		<li><a href=#>CLASSIC</a></li>
									<li><a href=#>DETECTIVE NOVEL</a></li>
									<li><a href=#>DRAMA AND ROMANCE</a></li>
									<li><a href=#>ACTION AND ADVERTURE</a></li>
									<li><a href="#">SCIENCE FICTION & FANTASY</a></li>
									<li><a href=#>HORROR</a></li>
							  </ul>
						 </li>               
						 <li class="dropdown1"><a href="#">LOG IN</a>
							 <ul class="dropdown2">
									<li><a href="registration.html">SING UP</a></li>
									<li><a href="#">CONTACT WITH US</a></li>
							  </ul>
						 </li>
						  <a class="shop" href="#"><img src="images/cart.png" alt=""/></a>
					  </ul>
				 </div>
				 <div class="clearfix"></div>
			 </div>
	  </div> 				 
</div>
<!--/banner-->
<div class="product">
	 <div class="container">
		 <div class="ctnt-bar cntnt">
			 <div class="content-bar">
				 <div class="single-page">
					 <div class="product-head">
						<a href="index.html">HОМЕ</a> <span>/</span>	
						<a href="bookstore.html">BOOKSTORE</a> <span>/</span>
						<a href="single.html"><%=@book.book_name%></a>
					</div>
					<!--//details-product-slider-->
					<div class="details-left-img">
						<img src= <%=  @book.photo%> class="img-responsive" />		
					 </div>
					 <div class="details-left-info">
							<h3><%=@book.book_name%></h3>
							<% @cats=[]
							 @book.categories.each do |cat| 
									@cats<<cat.category_name
							 end %>
								<h4><%=@cats.join("&")%></h4>
							<p><label>$</label> <%=@book.price%> <a href="#">Click for offer</a></p>
							<div class="rating">
								<span>☆</span><span>☆</span><span>☆</span><span>☆</span><span>☆</span>
								<p>   (<%=@book.rating%>/5)</p>
							</div>
							<div class="btn_form">
								<a href="cart.html">buy now</a>
								<a href="cart.html">ADD TO CART</a>
							</div>
							<div class="bike-type">
							<p>Год написания: <a href="#"><%=@book.publishing_year%></a></p>
							<p>Автор: <a> <%= link_to "#{@book.author.author_name}", @book.author %></a></p>
							</div>
							<h5>Описание:</h5>
							<p class="desc" align="justify"><%=@book.description%></p>
					 </div>
					 <div class="clearfix"></div>				 	
				  </div>
			  </div>
		  </div>
	 </div>
</div>
<!---->
<div class="footer">
	 <div class="container wrap">
		<div class="ftr-menu">
			 <ul>
			 	 <li><a href="index.html">HOME</a></li>
				 <li><a href="bookstore.html">BOOKSTORE</a></li>
				 <li><a href="categories.html">CATEGORIES</a></li>
				 <li><a href="#">LOG IN</a></li>
			 </ul>
		</div>
		<div class="clearfix"></div>
	 </div>
</div>
<!---->